config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flats
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<h2><%= flat.name %></h2>
<p><%= flat.address %></p>
<div id="info">
<ul>
<li><i class="fa-solid fa-user"></i> <%= flat.number_of_guests %> </li>
<li><i class="fa-solid fa-euro-sign"></i><%= flat.price_per_night %> </li>
</ul>
</div>

app/views/flats/index.html.erb
<h1>All our flats</h1>
<div id="flats">
  <% @flats.each do |flat| %>
  <div class="card" style="width: 18rem;">
    <%= render flat %>
    <p>
    <%= link_to "More info", flat %>
    </p>
  <% end %>
  <%= link_to "Add flat", new_flat_path %>
</div>

app/views/flats/new.html.erb
<%= simple_form_for [@flat] do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :description %>
<%= f.input :price_per_night %>
<%= f.input :number_of_guests %>
<%= f.submit %>
<i class="fa-solid fa-house"></i><%= link_to "Back home", @flat %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>